require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/story_ideas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StoryIdea. As you add validations to StoryIdea, be sure to
  # adjust the attributes here as well.
    let(:user) { create(:user) }
  let(:windows_type) { create(:windows_type) }
  let(:workshop) { create(:workshop) }
  let(:project) { create(:project) }

  let(:valid_attributes) do
    {
      title: "The Future of Festivals",
      body: "An exploration of how technology transforms community events.",
      publish_preferences: "I would like my full name published with the story",
      permission_given: true,
      windows_type_id: windows_type.id,
      workshop_id: workshop.id,
      project_id: project.id,
      created_by_id: user.id,
      updated_by_id: user.id
    }
  end

  let(:invalid_attributes) do
    {
      title: nil,                   # title is required
      body: "",                     # body cannot be blank
      publish_preferences: nil,     # missing preference
      created_by_id: nil            # missing creator
    }
  end

  before do
    sign_in user
  end

  describe "GET /index" do
    it "renders a successful response" do
      StoryIdea.create! valid_attributes
      get story_ideas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      story_idea = StoryIdea.create! valid_attributes
      get story_idea_url(story_idea)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_story_idea_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      story_idea = StoryIdea.create! valid_attributes
      get edit_story_idea_url(story_idea)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StoryIdea" do
        expect {
          post story_ideas_url, params: { story_idea: valid_attributes }
        }.to change(StoryIdea, :count).by(1)
      end

      it "redirects to the story_ideas index" do
        post story_ideas_url, params: { story_idea: valid_attributes }
        expect(response).to redirect_to(story_ideas_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new StoryIdea" do
        expect {
          post story_ideas_url, params: { story_idea: invalid_attributes }
        }.to change(StoryIdea, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post story_ideas_url, params: { story_idea: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested story_idea" do
        story_idea = StoryIdea.create! valid_attributes
        patch story_idea_url(story_idea), params: { story_idea: new_attributes }
        story_idea.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the story_idea" do
        story_idea = StoryIdea.create! valid_attributes
        patch story_idea_url(story_idea), params: { story_idea: new_attributes }
        story_idea.reload
        expect(response).to redirect_to(story_idea_url(story_idea))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        story_idea = StoryIdea.create! valid_attributes
        patch story_idea_url(story_idea), params: { story_idea: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested story_idea" do
      story_idea = StoryIdea.create! valid_attributes
      expect {
        delete story_idea_url(story_idea)
      }.to change(StoryIdea, :count).by(-1)
    end

    it "redirects to the story_ideas list" do
      story_idea = StoryIdea.create! valid_attributes
      delete story_idea_url(story_idea)
      expect(response).to redirect_to(story_ideas_url)
    end
  end
end
