require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tutorials", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Tutorial. As you add validations to Tutorial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: "How to Use the Dashboard",
      body: "<p>This tutorial walks through the main dashboard features.</p>",
      youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    }
  end

  let(:invalid_attributes) do
    {
      title: "",                # assuming presence validation
      body: nil,
      youtube_url: "not-a-url"  # fails URL validation if present
    }
  end

  let(:admin) { create(:user, :admin) }

  before do
    sign_in admin
  end

  describe "GET /index" do
    it "renders a successful response" do
      Tutorial.create! valid_attributes
      get tutorials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tutorial = Tutorial.create! valid_attributes
      get tutorial_url(tutorial)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tutorial_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tutorial = Tutorial.create! valid_attributes
      get edit_tutorial_url(tutorial)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tutorial" do
        expect {
          post tutorials_url, params: { tutorial: valid_attributes }
        }.to change(Tutorial, :count).by(1)
      end

      it "redirects to the tutorials index" do
        post tutorials_url, params: { tutorial: valid_attributes }
        expect(response).to redirect_to(tutorials_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tutorial" do
        expect {
          post tutorials_url, params: { tutorial: invalid_attributes }
        }.to change(Tutorial, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tutorials_url, params: { tutorial: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        valid_attributes.merge(
          title: "Updated: How to Use the Dashboard"
        )
      end

      it "updates the requested tutorial" do
        tutorial = Tutorial.create! valid_attributes
        patch tutorial_url(tutorial), params: { tutorial: new_attributes }
        tutorial.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tutorials index" do
        tutorial = Tutorial.create! valid_attributes
        patch tutorial_url(tutorial), params: { tutorial: new_attributes }
        tutorial.reload
        expect(response).to redirect_to(tutorials_url)
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tutorial = Tutorial.create! valid_attributes
        patch tutorial_url(tutorial), params: { tutorial: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tutorial" do
      tutorial = Tutorial.create! valid_attributes
      expect {
        delete tutorial_url(tutorial)
      }.to change(Tutorial, :count).by(-1)
    end

    it "redirects to the tutorials list" do
      tutorial = Tutorial.create! valid_attributes
      delete tutorial_url(tutorial)
      expect(response).to redirect_to(tutorials_url)
    end
  end
end
