require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  let(:valid_attributes) do
    {
      first_name: "Jane",
      last_name: "Doe",
      email: "jane.doe@example.com",
      password: "Password123!",
      password_confirmation: "Password123!"
    }
  end

  let(:invalid_attributes) do
    {
      first_name: "",
      last_name: nil,
      email: "invalid_email", # assuming format validation exists
      password: "short",
      password_confirmation: "different"
    }
  end

  before do
    admin_user = create(:user, :admin)
    sign_in admin_user
  end

  describe "GET /index" do
    it "renders a successful response" do
      User.create! valid_attributes
      get users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user = User.create! valid_attributes
      get user_url(user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user = User.create! valid_attributes
      get edit_user_url(user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User" do
        expect {
          post users_url, params: { user: valid_attributes }
        }.to change(User, :count).by(1)
      end

      it "redirects to the users index" do
        post users_url, params: { user: valid_attributes }
        expect(response).to redirect_to(users_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new User" do
        expect {
          post users_url, params: { user: invalid_attributes }
        }.to change(User, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post users_url, params: { user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        valid_attributes.merge(
          first_name: "Janet"
        )
      end

      it "updates the requested user" do
        user = User.create! valid_attributes
        patch user_url(user), params: { user: new_attributes }
        user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the users index" do
        user = User.create! valid_attributes
        patch user_url(user), params: { user: new_attributes }
        user.reload
        expect(response).to redirect_to(users_url)
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user = User.create! valid_attributes
        patch user_url(user), params: { user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    before do
      create(:user, :orphaned_reports) # so the deletion email can be triggered (before_destroy callback on user)
    end

    it "destroys the requested user" do
      user = User.create! valid_attributes
      expect {
        delete user_url(user)
      }.to change(User, :count).by(-1)
    end

    it "redirects to the users list" do
      user = User.create! valid_attributes
      delete user_url(user)
      expect(response).to redirect_to(users_url)
    end
  end

  describe "POST /toggle_lock_status" do
    context "when user is a super_user" do
      it "locks an unlocked user" do
        user = User.create! valid_attributes
        expect(user.locked_at).to be_nil
        post toggle_lock_status_user_url(user)
        user.reload
        expect(user.locked_at).not_to be_nil
        expect(response).to redirect_to(edit_user_url(user))
        expect(flash[:notice]).to eq("User has been locked.")
      end

      it "unlocks a locked user" do
        user = create(:user, :locked)
        expect(user.locked_at).not_to be_nil
        post toggle_lock_status_user_url(user)
        user.reload
        expect(user.locked_at).to be_nil
        expect(user.failed_attempts).to eq(0)
        expect(response).to redirect_to(edit_user_url(user))
        expect(flash[:notice]).to eq("User has been unlocked.")
      end
    end

    context "when user is not a super_user" do
      before do
        non_admin_user = create(:user)
        sign_in non_admin_user
      end

      it "redirects with an error message" do
        user = User.create! valid_attributes
        post toggle_lock_status_user_url(user)
        expect(response).to redirect_to(users_url)
        expect(flash[:alert]).to eq("You don't have permission to perform this action.")
      end

      it "does not change the user's lock status" do
        user = User.create! valid_attributes
        original_locked_at = user.locked_at
        post toggle_lock_status_user_url(user)
        user.reload
        expect(user.locked_at).to eq(original_locked_at)
      end
    end
  end

  describe "POST /confirm_email" do
    context "when user is a super_user" do
      it "confirms an unconfirmed email" do
        user = User.create! valid_attributes.merge(confirmed_at: nil)
        expect(user.confirmed_at).to be_nil
        post confirm_email_user_url(user)
        user.reload
        expect(user.confirmed_at).not_to be_nil
        expect(response).to redirect_to(edit_user_url(user))
        expect(flash[:notice]).to eq("Email has been manually confirmed.")
      end

      it "returns a message when email is already confirmed" do
        user = User.create! valid_attributes.merge(confirmed_at: Time.current)
        original_confirmed_at = user.confirmed_at
        post confirm_email_user_url(user)
        user.reload
        expect(user.confirmed_at).to eq(original_confirmed_at)
        expect(response).to redirect_to(edit_user_url(user))
        expect(flash[:notice]).to eq("Email is already confirmed.")
      end
    end

    context "when user is not a super_user" do
      before do
        non_admin_user = create(:user)
        sign_in non_admin_user
      end

      it "redirects with an error message" do
        user = User.create! valid_attributes
        post confirm_email_user_url(user)
        expect(response).to redirect_to(users_url)
        expect(flash[:alert]).to eq("You don't have permission to perform this action.")
      end

      it "does not change the user's confirmed_at status" do
        user = User.create! valid_attributes.merge(confirmed_at: nil)
        original_confirmed_at = user.confirmed_at
        post confirm_email_user_url(user)
        user.reload
        expect(user.confirmed_at).to eq(original_confirmed_at)
      end
    end
  end
end
