# Omakase Ruby styling for Rails

inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  action_policy: config/rubocop-rspec.yml

# Your own specialized rules go here
  #
  #
  #
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationWidth:
  Enabled: true
