# Inherit Shopify's Ruby style guide
inherit_gem:
  rubocop-shopify: rubocop.yml

# Load RuboCop extensions as plugins
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

# Custom project-specific overrides
AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

# Disable some rules that might be too strict for legacy code
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# RSPEC
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false
