FROM ruby:2.3

USER root

RUN apt-get update -qq && apt-get install -y qt5-default mysql-client libqtwebkit4 libqtwebkit-dev nodejs
RUN mkdir /app
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install --without development test
COPY . /app

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0", "-e", "development"]
