version: "3.7"

volumes:
  mysql-data:

services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: awbw_development
  web:
    build: "./"
    links:
      - database
    ports:
      - 3000:3000
    volumes: ['./:/app']
