FROM ruby:3.3.8

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  yarn \
  git \
  curl \
  imagemagick \
  libvips \
  tzdata \
  default-mysql-client \
  libxml2-dev \
  libxslt1-dev \
  libffi-dev \
  libreadline-dev \
  libssl-dev \
  zlib1g-dev 

WORKDIR /app

COPY . .

RUN bundle install
COPY . /app

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
