version: 2

jobs:
  deploy-staging:
    docker:
      - image: mehradm/awbworg:v1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "15:bf:72:7f:c7:2c:1c:65:3f:83:32:7f:34:85:fc:ba"

      - run: cap staging deploy

  deploy-production:
    docker:
      - image: mehradm/awbworg:v1

    steps:
      - checkout
      - run: ruby -v

workflows:
  version: 2
  deploy_staging_branch:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - deploy-staging:
          context: docker-hub-creds
          filters:
            branches:
              only: staging
  deploy_production_branch:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - deploy-production:
          context: docker-hub-creds
          filters:
            branches:
              only: production