require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/banners", type: :request do
    let(:admin) { create(:user, :admin) }

  let(:valid_attributes) do
    {
      content: "Welcome to AWBW!",
      show: true,
      created_by_id: admin.id,
      updated_by_id: admin.id
    }
  end

  let(:invalid_attributes) do
    { content: "", show: nil, created_by_id: nil, updated_by_id: nil }
  end

  before { sign_in admin } # Devise helper for authenticated routes

  describe "GET /index" do
    it "renders a successful response" do
      Banner.create! valid_attributes
      get banners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      banner = Banner.create! valid_attributes
      get banner_url(banner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_banner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      banner = Banner.create! valid_attributes
      get edit_banner_url(banner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Banner" do
        expect {
          post banners_url, params: { banner: valid_attributes }
        }.to change(Banner, :count).by(1)
      end

      it "redirects to the created banner" do
        post banners_url, params: { banner: valid_attributes }
        expect(response).to redirect_to(banners_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Banner" do
        expect {
          post banners_url, params: { banner: invalid_attributes }
        }.to change(Banner, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post banners_url, params: { banner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested banner" do
        banner = Banner.create! valid_attributes
        patch banner_url(banner), params: { banner: new_attributes }
        banner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the banner" do
        banner = Banner.create! valid_attributes
        patch banner_url(banner), params: { banner: new_attributes }
        banner.reload
        expect(response).to redirect_to(banner_url(banner))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        banner = Banner.create! valid_attributes
        patch banner_url(banner), params: { banner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested banner" do
      banner = Banner.create! valid_attributes
      expect {
        delete banner_url(banner)
      }.to change(Banner, :count).by(-1)
    end

    it "redirects to the banners list" do
      banner = Banner.create! valid_attributes
      delete banner_url(banner)
      expect(response).to redirect_to(banners_url)
    end
  end
end
