require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/community_news", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CommunityNews. As you add validations to CommunityNews, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CommunityNews.create! valid_attributes
      get community_news_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      community_news = CommunityNews.create! valid_attributes
      get community_news_url(community_news)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_community_news_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      community_news = CommunityNews.create! valid_attributes
      get edit_community_news_url(community_news)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CommunityNews" do
        expect {
          post community_news_index_url, params: { community_news: valid_attributes }
        }.to change(CommunityNews, :count).by(1)
      end

      it "redirects to the created community_news" do
        post community_news_index_url, params: { community_news: valid_attributes }
        expect(response).to redirect_to(community_news_url(CommunityNews.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CommunityNews" do
        expect {
          post community_news_index_url, params: { community_news: invalid_attributes }
        }.to change(CommunityNews, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post community_news_index_url, params: { community_news: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested community_news" do
        community_news = CommunityNews.create! valid_attributes
        patch community_news_url(community_news), params: { community_news: new_attributes }
        community_news.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the community_news" do
        community_news = CommunityNews.create! valid_attributes
        patch community_news_url(community_news), params: { community_news: new_attributes }
        community_news.reload
        expect(response).to redirect_to(community_news_url(community_news))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        community_news = CommunityNews.create! valid_attributes
        patch community_news_url(community_news), params: { community_news: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested community_news" do
      community_news = CommunityNews.create! valid_attributes
      expect {
        delete community_news_url(community_news)
      }.to change(CommunityNews, :count).by(-1)
    end

    it "redirects to the community_news list" do
      community_news = CommunityNews.create! valid_attributes
      delete community_news_url(community_news)
      expect(response).to redirect_to(community_news_index_url)
    end
  end
end
