require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/video_recordings", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # VideoRecording. As you add validations to VideoRecording, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: "How to Use the Home Page",
      body: "<p>This instructional video walks through the main home page features.</p>",
      youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    }
  end

  let(:invalid_attributes) do
    {
      title: "",                # assuming presence validation
      body: nil,
      youtube_url: "not-a-url"  # fails URL validation if present
    }
  end

  let(:admin) { create(:user, :admin) }

  before do
    sign_in admin
  end

  describe "GET /index" do
    it "renders a successful response" do
      VideoRecording.create! valid_attributes
      get video_recordings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      video_recording = VideoRecording.create! valid_attributes
      get video_recording_url(video_recording)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_video_recording_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      video_recording = VideoRecording.create! valid_attributes
      get edit_video_recording_url(video_recording)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VideoRecording" do
        expect {
          post video_recordings_url, params: { video_recording: valid_attributes }
        }.to change(VideoRecording, :count).by(1)
      end

      it "redirects to the created video_recording" do
        post video_recordings_url, params: { video_recording: valid_attributes }
        expect(response).to redirect_to(video_recording_url(VideoRecording.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VideoRecording" do
        expect {
          post video_recordings_url, params: { video_recording: invalid_attributes }
        }.to change(VideoRecording, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post video_recordings_url, params: { video_recording: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        valid_attributes.merge(
          title: "Updated: How to Use the Home Page"
        )
      end

      it "updates the requested video_recording" do
        video_recording = VideoRecording.create! valid_attributes
        patch video_recording_url(video_recording), params: { video_recording: new_attributes }
        video_recording.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the updated video_recording" do
        video_recording = VideoRecording.create! valid_attributes
        patch video_recording_url(video_recording), params: { video_recording: new_attributes }
        video_recording.reload
        expect(response).to redirect_to(video_recording_url(video_recording))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        video_recording = VideoRecording.create! valid_attributes
        patch video_recording_url(video_recording), params: { video_recording: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested video_recording" do
      video_recording = VideoRecording.create! valid_attributes
      expect {
        delete video_recording_url(video_recording)
      }.to change(VideoRecording, :count).by(-1)
    end

    it "redirects to the video_recordings list" do
      video_recording = VideoRecording.create! valid_attributes
      delete video_recording_url(video_recording)
      expect(response).to redirect_to(video_recordings_url)
    end
  end
end
