module NicknameMap
  # Maps canonical names to their common nicknames/variants.
  # All keys and values are lowercase.
  GROUPS = [
    # Nicknames and alternate spellings
    %w[abraham abe],
    %w[adelaida adela ada],
    %w[adolfo fito],
    %w[albert al bert],
    %w[alberto beto],
    %w[alejandra ale],
    %w[alejandro alex ale],
    %w[alexander alex xander],
    %w[alexandra alex alexa lexi],
    %w[alexis alex lexi],
    %w[alfonso poncho],
    %w[alfred al fred],
    %w[alfredo fredo],
    %w[alice ali alyce],
    %w[allison ali allie alison alyson],
    %w[amanda mandy],
    %w[amparo amparito],
    %w[anastasia ana stacy],
    %w[andrea andi],
    %w[andres andy],
    %w[andrew andy drew],
    %w[angela angie anjela],
    %w[ann annie anna anne],
    %w[anthony tony antony],
    %w[antonia toni toña],
    %w[antonio tony toño],
    %w[armando mando],
    %w[arthur art artie],
    %w[arturo turo art],
    %w[ashley ash ashlee ashleigh],
    %w[barbara barb barbie babs barbra],
    %w[beatrice bea beatriz betty],
    %w[benjamin ben benny],
    %w[bernardo bernie nardo],
    %w[bernard bernie],
    %w[blanca blanquita],
    %w[beverly bev],
    %w[bradley brad],
    %w[brian bryan],
    %w[bridget birdie bridgette brigid],
    %w[brittany britt brittney britney],
    %w[cameron cam camron kameron],
    %w[candace candy candice],
    %w[carlos carlitos],
    %w[carmen carmencita],
    %w[carolina carol carrie],
    %w[caroline carol carrie carolyn],
    %w[catalina cata],
    %w[catherine cathy cat kate katie kathy katherine kathryn],
    %w[cecilia ceci cecelia],
    %w[charles charlie chuck chas],
    %w[charlotte charlie lottie],
    %w[christina chris chrissie tina cristina kristine kristina],
    %w[christopher chris cristopher kristopher],
    %w[clarence clare],
    %w[clifford cliff],
    %w[concepcion concha conchita],
    %w[connor conor conner],
    %w[constance connie],
    %w[cristina cris tina],
    %w[cynthia cindy synthia],
    %w[daniel dan danny],
    %w[david dave davey],
    %w[deborah deb debbie debra],
    %w[delores dee lola],
    %w[dennis denny denis],
    %w[derek derrick],
    %w[diana di],
    %w[diego dieguito],
    %w[dolores lola dolly lolita],
    %w[domingo mingo],
    %w[donald don donnie],
    %w[dorothy dot dottie],
    %w[douglas doug],
    %w[eduardo edu lalo],
    %w[edward ed eddie ted teddy],
    %w[elena lena],
    %w[eleanor ellie elinor],
    %w[elizabeth liz beth lizzy eliza betsy libby elisabeth],
    %w[emily em emmy emilee emilie],
    %w[enrique quique kike],
    %w[eric erik erich],
    %w[ernesto neto],
    %w[esperanza espe],
    %w[esteban steve],
    %w[eugene gene],
    %w[evelyn ev evie],
    %w[federico fede],
    %w[felipe feli pipe],
    %w[fernando fer nando],
    %w[florence flo],
    %w[frances fran frannie],
    %w[francis frank fran],
    %w[francisco paco pancho frank],
    %w[franklin frank],
    %w[frederick fred freddy frederic],
    %w[gabriela gabby gabi],
    %w[gabriella gabby gabi],
    %w[gabriel gabe],
    %w[geoffrey geoff jeff jeffrey],
    %w[gerald jerry],
    %w[gerardo gerry],
    %w[geraldine geri jerry],
    %w[gertrude gert gertie trudy],
    %w[gloria glo],
    %w[graciela chela],
    %w[gregory greg gregg],
    %w[guadalupe lupe lupita],
    %w[guillermo memo],
    %w[gustavo gus tavo],
    %w[hailey hayley haley],
    %w[harold hal harry],
    %w[harriet hattie harriett],
    %w[heather heath],
    %w[hector hectorcito],
    %w[helen ellie],
    %w[henrietta hettie etta],
    %w[henry hank harry],
    %w[howard howie],
    %w[ignacio nacho],
    %w[irene rene],
    %w[isabel isa chabela isabelle],
    %w[isaiah zay],
    %w[isidro izzy],
    %w[jacqueline jackie jacquelyn jacklyn],
    %w[jaime jimmy],
    %w[james jim jimmy jamie],
    %w[jane janey],
    %w[janet jan janette],
    %w[janice jan],
    %w[jasmine jas jazz jazmine yasmin],
    %w[jason jay jayson],
    %w[javier javi],
    %w[jean jeanie],
    %w[jeffrey jeff geoffrey],
    %w[jennifer jen jenny jenifer],
    %w[jerome jerry],
    %w[jessica jess jessie jesica],
    %w[jesus chucho chuy],
    %w[joan joanie],
    %w[joanna jo johanna],
    %w[joaquin quino],
    %w[john jon johnny],
    %w[jonathan jon jonny john johnathan],
    %w[jorge george],
    %w[jose pepe chepe],
    %w[joseph joe joey],
    %w[josephine jo josie],
    %w[joshua josh],
    %w[juan juanito],
    %w[judith judy],
    %w[julian jules],
    %w[julianna julie juliana],
    %w[justin just],
    %w[karen kari karin caren],
    %w[katherine kathy kate katie kathryn catherine],
    %w[kathleen kathy kate katie],
    %w[katrina kat trina],
    %w[kayla kyla cayla],
    %w[kenneth ken kenny],
    %w[kimberly kim kimberley],
    %w[kristina kris tina christina],
    %w[kristin kris kristen],
    %w[larry lawrence],
    %w[laura laurie],
    %w[lawrence larry laurence],
    %w[leonardo leo nardo],
    %w[leonard leo lenny],
    %w[leticia lety],
    %w[leslie les lesley],
    %w[lillian lil lily lilian],
    %w[linda lin lynda],
    %w[lindsay lindsey lyndsey],
    %w[lorena lore],
    %w[louisa lou lulu],
    %w[louise lou],
    %w[lucia lucy luci],
    %w[lucille lucy],
    %w[luis lucho],
    %w[luisa luisita],
    %w[luz lucita lucy],
    %w[lydia liddy lidia],
    %w[madeline maddie madelyn madeleine],
    %w[manuel manny manu],
    %w[marc mark marcos],
    %w[margaret maggie meg peggy marge margie margret],
    %w[margarita mague maggie],
    %w[maria mari marita],
    %w[mariana mari],
    %w[marilyn mari lyn],
    %w[martha marty marta],
    %w[martin marty],
    %w[mateo matt],
    %w[mathew matt matthew],
    %w[maureen mo],
    %w[mauricio mauro],
    %w[maxwell max],
    %w[megan meg meghan meagan],
    %w[melanie mel melany],
    %w[melissa mel missy mellissa],
    %w[mercedes meche],
    %w[michael mike mikey micheal],
    %w[michelle shelly michele],
    %w[miguel mike migue],
    %w[mildred millie],
    %w[mitchell mitch],
    %w[monica moni monika],
    %w[nancy nan],
    %w[natalia naty],
    %w[natalie nat nathalie],
    %w[natasha tasha nat],
    %w[nathan nate],
    %w[nathaniel nate nat nathanial],
    %w[nicholas nick nicky nicolas nikolas],
    %w[nicole nikki nichole],
    %w[octavio tavo],
    %w[olivia liv],
    %w[oscar oscarito],
    %w[pablo pablito],
    %w[pamela pam],
    %w[patricia pat patty trish paty],
    %w[patricio pat pato],
    %w[patrick pat paddy],
    %w[pauline polly],
    %w[pedro pete],
    %w[penelope penny],
    %w[peter pete],
    %w[philip phil phillip],
    %w[priscilla cilla],
    %w[rachel rach rachael raquel],
    %w[rafael rafa rafe raphael],
    %w[ramiro rami],
    %w[ramon moncho],
    %w[randolph randy],
    %w[raul raulito],
    %w[raymond ray raymund],
    %w[rebecca becca becky rebekah rebeca],
    %w[reginald reggie],
    %w[ricardo ricky rick],
    %w[richard rich rick dick],
    %w[robert rob bob bobby robbie],
    %w[roberto beto rob],
    %w[roberta bobbie robbie],
    %w[rocio chayo],
    %w[rodney rod],
    %w[rodrigo rodri],
    %w[ronald ron ronnie],
    %w[rosa rosita],
    %w[rosalie rosie],
    %w[rosario charo],
    %w[rosemary rosie],
    %w[russell russ russel],
    %w[ruth ruthie],
    %w[ryan rian],
    %w[salvador chava],
    %w[samantha sam sammy],
    %w[samuel sam sammy],
    %w[sandra sandy],
    %w[santiago santi],
    %w[sara sarah],
    %w[sean shawn shaun],
    %w[sebastian seb],
    %w[sergio checo],
    %w[sharon shari],
    %w[sheldon shel],
    %w[silvia silvita sylvia],
    %w[socorro coco],
    %w[sofia sophie sophia],
    %w[stanley stan],
    %w[stefanie steph stephanie],
    %w[stephen steve steven stefan],
    %w[susan sue susie suzan],
    %w[suzanne sue suzy susanne],
    %w[teresa tere terri tess theresa],
    %w[theodore ted teddy theo],
    %w[thomas tom tommy tomas],
    %w[timothy tim timmy],
    %w[valeria vale val],
    %w[valerie val],
    %w[vanessa nessa vane],
    %w[veronica ronnie roni vero],
    %w[victoria vicky tori],
    %w[vincent vince vinny],
    %w[virginia ginny],
    %w[vivian viv viviana vivianne vivienne],
    %w[walter walt wally],
    %w[wendy wen],
    %w[william will bill billy liam willy],
    %w[ximena xime],
    %w[yolanda yoli],
    %w[zachary zach zack zac zackary zackery zachery]
  ].freeze

  # Build a lookup: given any name in a group, return all names in that group.
  LOOKUP = begin
    map = Hash.new { |h, k| h[k] = Set.new }
    GROUPS.each do |group|
      group.each do |name|
        group.each { |variant| map[name] << variant }
      end
    end
    map.transform_values(&:to_a).freeze
  end

  # Returns an array of name variants (including the input itself).
  # e.g. variants_for("Bob") => ["robert", "rob", "bob", "bobby", "robbie"]
  def self.variants_for(name)
    LOOKUP.fetch(name.to_s.downcase, [ name.to_s.downcase ])
  end
end
