base: &base
  adapter: trilogy
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  url: <%= ENV.fetch("DATABASE_URL", "trilogy://root@localhost") %>

default: &default
  adapter: trilogy
  encoding: utf8mb4           # <-- forces UTF-8 everywhere
  collation: utf8mb4_unicode_ci  # <-- portable across MySQL 5.7/8.0 and MariaDB
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  user: root
  password:
  host: 127.0.0.1
  variables:
    # Make sure the session uses utf8mb4 too:
    collation_connection: utf8mb4_unicode_ci
    sql_mode: STRICT_ALL_TABLES

development:
  <<: *default
  database: awbw_development

test:
  <<: *default
  database: awbw_test
