# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073748185a3133f55a4aed7c2729ca16d195d7ab665e88627d024224888f2b83c2d9ea88d2fe672357945f41c411a7aa3953f1e751f57730987e556f7203574f
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  default_to_email: denman@zehnergroup.com

test:
  secret_key_base: 21c98cdbd879e054be603566c0720eab2b87497ee6e87487b8bd49877fd6a1209801160735b522ac71c87763737bdec33f93e2f68b64d4a2ba9918de19ef0152

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  default_to_email: rhernandez@awbw.org

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  default_to_email: rhernandez@awbw.org

